---
version: '3.9'
services:
  db:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - tododb:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  tododb:
